###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"teja",
    "username":"teja123",
    "password": "teja@456",
    "gender": "Female",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"teja123",
    "password": "teja@46"
}